export const TIMEQUANT = "120";
export const ARENALOT_CREATOR = "0xbAEBD3b1F59F7A91E8177A8eDaBe02EAA1C17bED";
export const SECONDS_IN_DAY = "86400";
export const SECONDS_IN_WEEK = "604800";

export const STOCK_TOKENS = [
  "dowjones",
  "snp500",
  "nasdaq",
  "nikkei",
  "hangseng",
  "ftse",
  "cac40",
  "dax",
  "dxy",
];
export const COMMODITY_TOKENS = [
  "snpgold",
  "snpsilver",
  "snpaluminum",
  "snpcrudeoil",
  "snpmaturalgas",
];
export const FOREX_TOKENS = [
  "eur-usd",
  "aud-usd",
  "gbp-usd",
  "jpy-usd",
  "nzd-usd",
  "chf-usd",
  "cad-usd",
];
export const NFT_TOKENS = [
    'coolcats',
    'azuki',
    'otherdeed',
    'clonex',
    'moonbirds',
    'milady',
    'bayc',
    'mayc',
    'pudgypenguins',
    'beanz',
    'doodles',
    'valhalla',
    'degods',
    'meebits',
    'rektguy',
    'invisiblefriends',
    'captainz',
    'yayo'
];
export const CRYPTO_TOKENS = [
  "ethereum",
  "solana",
  "cardano",
  "avalanche-2",
  "chainlink",
  "algorand",
  "matic-network",
  "fantom",
  "qtum",
  "kadena",
  "omisego",
  "chromaway",
  "oasis-network",
  "ethereum-classic",
  "tezos",
  "eos",
  "near",
  "neo",
  "harmony",
  "tron",
  "stellar",
  "internet-computer",
  "velas",
  "bitcoin",
  "ripple",
  "litecoin",
  "the-open-network",
  "leo-token",
  "bitcoin-cash",
  "hedera-hashgraph",
  "quant-network",
  "blockstack",
  "elrond-erd-2",
  "theta-token",
  "maker",
  "rocket-pool",
  "mina-protocol",
  "dash",
  "klay-token",
  "singularitynet",
  "zcash",
  "zilliqa",
  "fetch-ai",
  "convex-finance",
  "conflux-token",
  "ethereum-name-service",
  "nexo",
  "yearn-finance",
  "ssv-network",
  "magic",
  "blur",
  "astar",
  "stepn",
  "synapse-2",
  "zelcash",
  "gains-network",
  "compound-governance-token",
  "bonk",
  "the-graph",
  "polkadot",
  "canto",
  "aptos",
  "optimism",
  "loopring",
  "immutable-x",
  "metis-token",
  "uniswap",
  "gmx",
  "aave",
  "havven",
  "curve-dao-token",
  "lido-dao",
  "binancecoin",
  "crypto-com-chain",
  "okb",
  "huobi-token",
  "kucoin-shares",
  "mx-token",
  "pancakeswap-token",
  "dydx",
  "woo-network",
  "1inch",
  "osmosis",
  "sushi",
  "quickswap",
  "camelot-token",
  "cosmos",
  "ontology",
  "injective-protocol",
  "waves",
  "audius",
  "serum",
  "raydium",
  "kusama",
  "ankr",
  "moonbeam",
  "dogecoin",
  "shiba-inu",
  "dogelon-mars",
  "floki",
  "decentraland",
  "render-token",
  "mask-network",
  "wilder-world",
  "enjincoin",
  "the-sandbox",
  "illuvium",
  "axie-infinity",
  "thorchain",
  "secret",
  "band-protocol",
  "kava",
  "vulcan-forged",
  "gala",
  "apecoin",
  "yield-guild-games",
  "verasity",
  "frax-share",
  "joe",
  "bluzelle",
  "api3",
  "uma",
  "wink",
  "iexec-rlc",
  "nest",
  "filecoin",
  "arweave",
  "holotoken",
  "siacoin",
  "ocean-protocol",
  "storj",
  "monero",
  "decred",
  "zencash",
  "nucypher",
  "digibyte",
  "flow",
  "chiliz",
  "paris-saint-germain-fan-token",
  "manchester-city-fan-token",
  "fc-barcelona-fan-token",
  "juventus-fan-token",
  "atletico-madrid",
  "ac-milan-fan-token",
  "galatasaray-fan-token",
  "inter-milan-fan-token",
  "biconomy",
  "arbitrum",
  "arbdoge-ai",
  "pepe",
  "space-id",
  "zoid-pay",
  "radiant-capital",
  "tominet",
  "kaspa",
  "arsenal-fan-token",
  "icon",
  "ordinals",
  "meme-brc-20",
  "vmpx",
  "ben-2",
  "jeff",
];

export const INDEX_TOKENS = [
  "l1-index",
  "l2-index",
  "defi-index",
  "cex-index",
  "dex-index",
  "bsc-index",
  "solana-index",
  "polkadot-index",
  "meme-index",
  "polygon-index",
  "metaverse-index",
  "cosmos-index",
  "gaming-index",
  "avalanche-index",
  "onp-index",
  "storage-index",
  "privacy-index",
  "sports-index",
];

export function getTokenType(Token: string): string {
  if (STOCK_TOKENS.indexOf(Token) != -1) {
    return "stock";
  } else if (COMMODITY_TOKENS.indexOf(Token) != -1) {
    return "commodity";
  } else if (FOREX_TOKENS.indexOf(Token) != -1) {
    return "forex";
  } else if (NFT_TOKENS.indexOf(Token) != -1) {
    return "ethnft";
  } else if (CRYPTO_TOKENS.indexOf(Token) != -1) {
    return "crypto";
  } else if (INDEX_TOKENS.indexOf(Token) != -1) {
    return "index";
  } else {
    return "none";
  }
}
